project:
  type: book
  output-dir: docs

book:
  title: "Using geoparquet with R"
  author: "Ryan Peek"
  date: "2023-04-20"
  
  search: true
  repo-url: https://github.com/d-rug/using-geoparquet-R
  downloads: [pdf]
  chapters:
    - index.qmd
    - demo.qmd

  sidebar:
    logo: https://github.com/d-rug/d-rug.github.io/raw/main/DRUG_final_cobalt.png
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: false